// AUTO-GENERATED by web/scripts/gen-contract.mjs.
// Do not edit manually. Re-run `npm run gen:contract` from /web.
// Source of truth: web/src/lib/contract/ws.ts
//
// Server->Client tags: 16
// Client->Server tags: 31
#pragma once

#include <stddef.h>
#include <stdint.h>
#include <string.h>

namespace WsContract {

enum class ServerMessage : uint8_t {
    Pong = 0,
    Sensors = 1,
    SensorConfig = 2,
    Devices = 3,
    DeviceModes = 4,
    ClimateConfig = 5,
    Events = 6,
    Event = 7,
    Energy = 8,
    Dli = 9,
    History = 10,
    PpfdCalibration = 11,
    SystemInfo = 12,
    ClearHistory = 13,
    Restart = 14,
    OtaStatus = 15,
};

constexpr const char* kServerMessageNames[] = {
    "pong",
    "sensors",
    "sensor_config",
    "devices",
    "device_modes",
    "climate_config",
    "events",
    "event",
    "energy",
    "dli",
    "history",
    "ppfd_calibration",
    "system_info",
    "clear_history",
    "restart",
    "ota_status",
};
constexpr size_t kServerMessageNamesCount = 16;

inline bool tryParseServerMessage(const char* tag, ServerMessage& out) {
    if (!tag) return false;
    for (size_t i = 0; i < kServerMessageNamesCount; ++i) {
        if (strcmp(tag, kServerMessageNames[i]) == 0) {
            out = static_cast<ServerMessage>(i);
            return true;
        }
    }
    return false;
}
inline const char* nameOf(ServerMessage v) {
    auto i = static_cast<size_t>(v);
    return i < kServerMessageNamesCount ? kServerMessageNames[i] : "";
}

enum class ClientMessage : uint8_t {
    Ping = 0,
    GetInit = 1,
    GetDeviceModes = 2,
    GetDevices = 3,
    GetSensors = 4,
    GetPpfdCalibration = 5,
    GetEnergy = 6,
    GetDli = 7,
    GetClimateConfig = 8,
    GetEvents = 9,
    ClearEvents = 10,
    GetSystemInfo = 11,
    ResetDli = 12,
    ResetPpfdCalibration = 13,
    ClearHistory = 14,
    Restart = 15,
    GetHistory = 16,
    DeviceControl = 17,
    SetDeviceMode = 18,
    DeleteDeviceMode = 19,
    AddDevice = 20,
    UpdateDevice = 21,
    RemoveDevice = 22,
    AddSensor = 23,
    UpdateSensor = 24,
    RemoveSensor = 25,
    CalibratePpfd = 26,
    ResetEnergy = 27,
    SetClimatePhase = 28,
    SetClimateTargets = 29,
    ResetClimateTargets = 30,
};

constexpr const char* kClientMessageNames[] = {
    "ping",
    "get_init",
    "get_device_modes",
    "get_devices",
    "get_sensors",
    "get_ppfd_calibration",
    "get_energy",
    "get_dli",
    "get_climate_config",
    "get_events",
    "clear_events",
    "get_system_info",
    "reset_dli",
    "reset_ppfd_calibration",
    "clear_history",
    "restart",
    "get_history",
    "device_control",
    "set_device_mode",
    "delete_device_mode",
    "add_device",
    "update_device",
    "remove_device",
    "add_sensor",
    "update_sensor",
    "remove_sensor",
    "calibrate_ppfd",
    "reset_energy",
    "set_climate_phase",
    "set_climate_targets",
    "reset_climate_targets",
};
constexpr size_t kClientMessageNamesCount = 31;

inline bool tryParseClientMessage(const char* tag, ClientMessage& out) {
    if (!tag) return false;
    for (size_t i = 0; i < kClientMessageNamesCount; ++i) {
        if (strcmp(tag, kClientMessageNames[i]) == 0) {
            out = static_cast<ClientMessage>(i);
            return true;
        }
    }
    return false;
}
inline const char* nameOf(ClientMessage v) {
    auto i = static_cast<size_t>(v);
    return i < kClientMessageNamesCount ? kClientMessageNames[i] : "";
}

} // namespace WsContract
